-- =====================================================
-- ADATBÁZIS STRUKTÚRA
-- =====================================================

-- Kategóriák tábla
CREATE TABLE IF NOT EXISTS `kategoriak` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nev` varchar(100) COLLATE utf8mb4_hungarian_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

-- Kiadók tábla
CREATE TABLE IF NOT EXISTS `kiadok` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nev` varchar(255) COLLATE utf8mb4_hungarian_ci NOT NULL,
  `szekhely` varchar(255) COLLATE utf8mb4_hungarian_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

-- Szerzők tábla
CREATE TABLE IF NOT EXISTS `szerzok` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nev` varchar(255) COLLATE utf8mb4_hungarian_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

-- Könyvek tábla
CREATE TABLE IF NOT EXISTS `konyvek` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `cim` varchar(255) COLLATE utf8mb4_hungarian_ci NOT NULL,
  `kep` varchar(255) COLLATE utf8mb4_hungarian_ci DEFAULT NULL,
  `leiras` text COLLATE utf8mb4_hungarian_ci DEFAULT NULL,
  `szerzo_id` int DEFAULT NULL,
  `kiado_id` int DEFAULT NULL,
  `kategoria_id` int DEFAULT NULL,
  `ISBN` varchar(13) COLLATE utf8mb4_hungarian_ci DEFAULT NULL,
  `konyvtar_nyilvantartasi_szam` varchar(255) COLLATE utf8mb4_hungarian_ci DEFAULT NULL,
  `keszlet` int NOT NULL DEFAULT 1,
  `kolcsonozheto` tinyint(1) NOT NULL DEFAULT 1,
  `beszerzesi_ar` decimal(10,2) DEFAULT NULL,
  `kiadas_ev` smallint DEFAULT NULL,
  `magassag_cm` decimal(5,2) DEFAULT NULL,
  `csillag_ertekeles` decimal(2,1) NOT NULL DEFAULT 0.0,
  FOREIGN KEY (`szerzo_id`) REFERENCES `szerzok`(`id`),
  FOREIGN KEY (`kiado_id`) REFERENCES `kiadok`(`id`),
  FOREIGN KEY (`kategoria_id`) REFERENCES `kategoriak`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

-- =====================================================
-- ALAPADATOK BESZÚRÁSA (kategóriák, szerzők, kiadók)
-- =====================================================

-- Kategóriák
INSERT INTO `kategoriak` (`id`, `nev`) VALUES
(1, 'Szépirodalom'),
(2, 'Szakácskönyv'),
(3, 'Romantikus'),
(4, 'Fantasy'),
(5, 'Sci-fi'),
(6, 'Krimi / Thriller'),
(7, 'Történelem'),
(8, 'Életmód / Egészség'),
(9, 'Ifjúsági'),
(10, 'Horror'),
(11, 'Önéletrajz / Életrajz'),
(12, 'Vers'),
(13, 'Gasztronómia'),
(14, 'Pszichológia'),
(15, 'Üzlet / Önfejlesztés');

-- Szerzők (placeholder szerzők)
INSERT INTO `szerzok` (`id`, `nev`) VALUES
(1, 'Ismeretlen szerző'),
(2, 'George Orwell'),
(3, 'Andy Weir'),
(4, 'Rebecca Yarros'),
(5, 'Colleen Hoover'),
(6, 'Sarah J. Maas'),
(7, 'Stephen King'),
(8, 'J. R. R. Tolkien'),
(9, 'Jane Austen'),
(10, 'Agatha Christie');

-- Kiadók
INSERT INTO `kiadok` (`id`, `nev`, `szekhely`) VALUES
(1, 'Ismeretlen kiadó', NULL),
(2, 'Európa Könyvkiadó', 'Budapest'),
(3, 'Magvető Kiadó', 'Budapest'),
(4, 'Helikon Kiadó', 'Budapest'),
(5, 'Alexandra Kiadó', 'Pécs'),
(6, 'Kossuth Kiadó', 'Budapest'),
(7, 'General Press', 'Budapest'),
(8, 'HVG Könyvek', 'Budapest'),
(9, 'Libri Kiadó', 'Budapest'),
(10, 'Gabo Kiadó', 'Budapest');

-- =====================================================
-- KÖNYVEK BESZÚRÁSA (kiterjesztéssel együtt)
-- =====================================================

INSERT INTO `konyvek` (`cim`, `kep`, `leiras`, `szerzo_id`, `kiado_id`, `kategoria_id`, `keszlet`, `kolcsonozheto`, `csillag_ertekeles`) VALUES
('1984', '1984.jpg', 'Disztópikus regény a totális megfigyelésről.', 2, 2, 1, 3, 1, 4.5),
('500 gramm zöldség mindennap, változatosan', '500 gramm zöldség mindennap, változatosan.jpg', NULL, 1, 6, 2, 2, 1, 0.0),
('500 saláta', '500 saláta.jpg', NULL, 1, 6, 2, 2, 1, 0.0),
('500 smoothie és turmix', '500 smoothie és turmix.jpg', NULL, 1, 6, 2, 2, 1, 0.0),
('A Biblia ételei', 'A Biblia ételei.jpg', NULL, 1, 5, 2, 1, 1, 0.0),
('A bosszú otthona', 'A bosszú otthona.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('A Court of Silver Flames - Ezüst lángok udvara', 'A Court of Silver Flames - Ezüst lángok udvara.jpg', NULL, 6, 4, 4, 2, 1, 4.8),
('A Court of Wings and Ruin - Szárnyak és pusztulás udvara', 'A Court of Wings and Ruin - Szárnyak és pusztulás udvara.jpg', NULL, 6, 4, 4, 2, 1, 4.7),
('A Crown This Cold And Heavy - Oly hideg és nehéz korona', 'A Crown This Cold And Heavy - Oly hideg és nehéz korona.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('A diétás beteg szakácskönyve - Változatos étrendek', 'A diétás beteg szakácskönyve - Változatos étrendek.jpg', NULL, 1, 8, 8, 1, 1, 0.0),
('A fogoly', 'A fogoly.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('A forrás nem kérdi, merre visz az útja', 'A forrás nem kérdi, merre visz az útja.jpg', NULL, 1, 3, 1, 1, 1, 0.0),
('A francia konyha művészete', 'A francia konyha művészete.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('A fémjelzett ember', 'A fémjelzett ember.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('A földrajz fogságában', 'A földrajz fogságában.jpg', NULL, 1, 9, 7, 1, 1, 0.0),
('A föld nyelte el', 'A föld_nyelte_el.jpg', NULL, 1, 9, 10, 1, 1, 0.0),
('A fűszer nagykönyve', 'A fűszer nagykönyve.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('A Gonosz bűntársa', 'A Gonosz bűntársa.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('A győztes étrend', 'A győztes étrend.jpg', NULL, 1, 8, 8, 1, 1, 0.0),
('A Hail Mary-küldetés', 'A Hail Mary-küldetés.jpg', NULL, 3, 2, 5, 2, 1, 4.6),
('A herceg és én', 'A herceg és én.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('A hivatalos Bridgerton szakácskönyv', 'A hivatalos Bridgerton szakácskönyv.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('A háború művészete', 'A háború művészete.jpg', NULL, 1, 7, 15, 2, 1, 4.2),
('A kert konyhája', 'A kert konyhája.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('A Kilimandzsáró felett az ég', 'A Kilimandzsáró felett az ég.jpg', NULL, 1, 3, 1, 1, 1, 0.0),
('A kutya vacsorája', 'A kutya vacsorája.jpg', NULL, 1, 5, 2, 1, 1, 0.0),
('A lány hét névvel', 'A lány hét névvel.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('A magabiztos szülő', 'A magabiztos szülő.jpg', NULL, 1, 8, 8, 1, 1, 0.0),
('A marsi - Mentőexpedíció', 'A marsi - Mentőexpedíció.jpg', NULL, 3, 2, 5, 2, 1, 4.7),
('A megtévesztés foka', 'A megtévesztés foka.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('A merénylet', 'A merénylet.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('A mi süteményeskönyvünk', 'A mi süteményeskönyvünk.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('A másik mozaik', 'A másik mozaik.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('A nagy wok szakácskönyv', 'A nagy wok szakácskönyv.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('A Street Kitchen bemutatja', 'A Street Kitchen bemutatja.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('A szerelemnél nincs szörnyűbb átok', 'A szerelemnél nincs szörnyűbb átok.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('A sárkány végzete', 'A sárkány végzete.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('A templomosok', 'A templomosok.jpg', NULL, 1, 7, 7, 1, 1, 0.0),
('A tenger nővérei', 'A tenger nővérei.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('A tökéletes házasság', 'A tökéletes házasság.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('A valódi James Bond', 'A valódi James Bond.jpg', NULL, 1, 11, 1, 1, 1, 0.0),
('A vágy tüzében', 'A vágy tüzében.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('A végítélet forgatókönyve', 'A végítélet forgatókönyve.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('A víz szövetsége', 'A víz szövetsége.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('A zárda gyermekei - Lottie Parker 15.', 'A zárda gyermekei - Lottie Parker 15..jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Adjuk meg a módját!', 'Adjuk meg a módját!.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Air fryer - A sütés forradalma', 'Air fryer - A sütés forradalma.jpg', NULL, 1, 6, 2, 2, 1, 4.3),
('Air Fryer kezdőknek', 'Air Fryer kezdőknek.jpg', NULL, 1, 6, 2, 2, 1, 4.0),
('Air fryer szakácskönyv', 'Air fryer szakácskönyv.jpg', NULL, 1, 6, 2, 2, 1, 4.1),
('Alchemised - Alkimisták háborúja', 'Alchemised - Alkimisták háborúja.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Almásrétes-alibi', 'Almásrétes-alibi.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Alvilági románc 5. - Broken Vow', 'Alvilági románc 5. - Broken Vow.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Anya, kérek még! - bővített kiadás', 'Anya, kérek még! - bővített kiadás.jpg', NULL, 1, 8, 8, 1, 1, 0.0),
('Anya, írtam egy könyvet rólad', 'Anya, írtam egy könyvet rólad.jpg', NULL, 1, 8, 11, 1, 1, 0.0),
('Arafat harcosa voltam', 'Arafat harcosa voltam.jpg', NULL, 1, 11, 11, 1, 1, 0.0),
('Artemis', 'Artemis.jpg', NULL, 3, 2, 5, 1, 1, 4.4),
('Autoimmun szakácskönyv', 'Autoimmun szakácskönyv.jpg', NULL, 1, 8, 2, 1, 1, 0.0),
('Az eltűnő Cseresznyevirág Könyvesbolt', 'Az eltűnő Cseresznyevirág Könyvesbolt.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Az ismeretlen Szahara', 'Az ismeretlen Szahara.jpg', NULL, 1, 7, 7, 1, 1, 0.0),
('Az iszlám', 'Az iszlám.jpg', NULL, 1, 7, 7, 1, 1, 0.0),
('Az ég minden kékje', 'Az ég minden kékje.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Az éhes lélek gyógyítása - Túlsúly, evészavarok és kapcsolati problémák', 'Az éhes lélek gyógyítása - Túlsúly, evészavarok és kapcsolati problémák.jpg', NULL, 1, 14, 14, 1, 1, 0.0),
('Az éjszaka iskolája', 'Az éjszaka iskolája.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Az én alapszakácskönyvem', 'Az én alapszakácskönyvem.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('Az én itáliai konyhám', 'Az én itáliai konyhám.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('Az én kék zónám', 'Az én kék zónám.jpg', NULL, 1, 8, 8, 1, 1, 0.0),
('Az összes nyarunk', 'Az összes nyarunk.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('a titkok titka', 'a_titkok_titka.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Bea konyhája 5.', 'Bea konyhája 5..jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('Beautiful Venom', 'Beautiful Venom.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Bellevue', 'Bellevue.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Binding 13 - Kötés 13 - (Különleges kiadás)', 'Binding 13 - Kötés 13 - (Különleges kiadás).jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Binding 13', 'Binding 13.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Born of Blood and Ash - Vérből és hamuból született', 'Born of Blood and Ash - Vérből és hamuból született.jpg', NULL, 6, 4, 4, 1, 1, 0.0),
('Botrányos örökös', 'Botrányos örökös.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Bulldozer - Buldózer', 'Bulldozer - Buldózer.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Bíboralkony', 'Bíboralkony.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Búcsú nélkül eltűntél', 'Búcsú nélkül eltűntél.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Bűnhődj értem', 'Bűnhődj értem.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('City of Ruin - Romváros - (Különleges kiadás)', 'City of Ruin - Romváros - (Különleges kiadás).jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Coach - Az edző', 'Coach - Az edző.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Colette', 'Colette.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Csoda', 'Csoda.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Dacszövetség 5.', 'Dacszövetség 5..jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Daughter of No Worlds - A hontalanság lánya', 'Daughter of No Worlds - A hontalanság lánya.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Dire Bound - A farkas köteléke', 'Dire Bound - A farkas köteléke.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Dr. Mengele boncolóorvosa voltam az auschwitzi krematóriumban', 'Dr. Mengele boncolóorvosa voltam az auschwitzi krematóriumban.jpg', NULL, 1, 11, 11, 1, 1, 0.0),
('Drumindor', 'Drumindor.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Dubaj gésái 2.', 'Dubaj gésái 2..jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Egy emlékirat könyve', 'Egy emlékirat könyve.jpg', NULL, 1, 9, 11, 1, 1, 0.0),
('Egy ropi naplója 20. - Partiarc', 'Egy ropi naplója 20. - Partiarc.jpg', NULL, 1, 9, 9, 2, 1, 0.0),
('Elvonókúra', 'Elvonókúra.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Emberi rabság', 'Emberi rabság.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Emma - (Különleges kiadás)', 'Emma - (Különleges kiadás).jpg', NULL, 9, 4, 3, 1, 1, 4.6),
('Evil Boys', 'Evil Boys.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Ezüst hattyú', 'Ezüst hattyú.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Fourth Wing - Negyedik szárny', 'Fourth Wing - Negyedik szárny.jpg', NULL, 4, 4, 4, 3, 1, 4.9),
('Fourth Wing', 'Fourth Wing.jpg', NULL, 4, 4, 4, 3, 1, 4.9),
('Grim and Oro', 'Grim and Oro.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Halálos fehér', 'Halálos fehér.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Hideg polgárháború', 'Hideg polgárháború.jpg', NULL, 1, 9, 7, 1, 1, 0.0),
('Hitel 2026. április - Irodalmi, társadalmi és művészeti folyóirat', 'Hitel 2026. április - Irodalmi, társadalmi és művészeti folyóirat.jpg', NULL, 1, 3, 12, 1, 1, 0.0),
('Holdnővér', 'Holdnővér.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Honvágy', 'Honvágy.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Hopeless - Reménytelen', 'Hopeless - Reménytelen.jpg', NULL, 5, 7, 3, 2, 1, 4.5),
('Horváth Ilona illusztrált szakácskönyve', 'Horváth Ilona illusztrált szakácskönyve.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('How My Neighbor Stole Christmas', 'How My Neighbor Stole Christmas.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Hozzátáplálási napló', 'Hozzátáplálási napló.jpg', NULL, 1, 8, 8, 1, 1, 0.0),
('Ház a világ végén', 'Ház a világ végén.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Hérodotosztól Harariig', 'Hérodotosztól Harariig.jpg', NULL, 1, 7, 7, 1, 1, 0.0),
('Hét halálos tövis', 'Hét halálos tövis.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Hét perc - Dedikált', 'Hét perc - Dedikált.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Hódítók', 'Hódítók.jpg', NULL, 1, 9, 7, 1, 1, 0.0),
('Hőhullámon', 'Hőhullámon.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Into the Tide - Sodrásban', 'Into the Tide - Sodrásban.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Iron Flame - Vasláng', 'Iron Flame - Vasláng.jpg', NULL, 4, 4, 4, 3, 1, 4.8),
('Jakuza - Festék a bőrön', 'Jakuza - Festék a bőrön.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('John - Connor fivérek II', 'John - Connor fivérek II.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Jóbarátok - A hivatalos szakácskönyv - füles, kartonált', 'Jóbarátok - A hivatalos szakácskönyv - füles, kartonált.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('Kimenekítés', 'Kimenekítés.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Kovászkaland', 'Kovászkaland.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('Ködös Balaton', 'Ködös Balaton.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Lessons In Faking - Színlelésből jeles', 'Lessons In Faking - Színlelésből jeles.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Limara Péksége', 'Limara Péksége.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Lindt & Sprüngli 2. - Két rivális, egy álom', 'Lindt & Sprüngli 2. - Két rivális, egy álom.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Londoni levelek', 'Londoni levelek.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Londonsztori', 'Londonsztori.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Lunchbox', 'Lunchbox.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('Luxemburgi Zsigmond uralkodása 1387-1437', 'Luxemburgi Zsigmond uralkodása 1387-1437.jpg', NULL, 1, 7, 7, 1, 1, 0.0),
('Lázár', 'Lázár.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Magasan a nyeregben', 'Magasan a nyeregben.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Magyar superfood', 'Magyar superfood.jpg', NULL, 1, 8, 2, 1, 1, 0.0),
('Megőrülök érted', 'Megőrülök érted.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Men with the pot - Grill szakácskönyv', 'Men with the pot - Grill szakácskönyv.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('Millenniumi napló', 'Millenniumi napló.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Mindenek hajnala', 'Mindenek hajnala.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Mondd meg a méheknek, hogy nem térek vissza - kemény kötés', 'Mondd meg a méheknek, hogy nem térek vissza - kemény kötés.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('My December Darling - Szerelmes karácsony', 'My December Darling - Szerelmes karácsony.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('My Return to the Walter Boys', 'My Return to the Walter Boys.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Mythica - Legendás hősnők igaz története', 'Mythica - Legendás hősnők igaz története.jpg', NULL, 1, 7, 7, 1, 1, 0.0),
('Még egyszer', 'Még egyszer.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Nagy whiskykalauz', 'Nagy whiskykalauz.jpg', NULL, 1, 6, 13, 1, 1, 0.0),
('Ne tágíts', 'Ne tágíts.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Nekik mindegy - A közösségi média cápái testközelbő', 'Nekik mindegy - A közösségi média cápái testközelbő.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('No Broken Beast - Nem sebzett fenevad', 'No Broken Beast - Nem sebzett fenevad.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Nyom nélkül', 'Nyom nélkül.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Pen Pal - Levelezőtárs', 'Pen Pal - Levelezőtárs.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Pipp és Polli - Az érzelmek nagy könyve', 'Pipp és Polli - Az érzelmek nagy könyve.jpg', NULL, 1, 9, 9, 1, 1, 0.0),
('Problémás nyári románc', 'Problémás nyári románc.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Prédák háza', 'Prédák háza.jpg', NULL, 1, 9, 10, 1, 1, 0.0),
('Pusztítás', 'Pusztítás.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Redeeming 6 - Megváltás 6', 'Redeeming 6 - Megváltás 6.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Reminders of Him - Emlékek róla - Filmes borító', 'Reminders of Him - Emlékek róla - Filmes borító.jpg', NULL, 5, 7, 3, 2, 1, 4.4),
('Restitution', 'Restitution.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Revolve - Fordulat', 'Revolve - Fordulat.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Romváros', 'Romváros.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Ruthless Creatures - Könyörtelen teremtmények', 'Ruthless Creatures - Könyörtelen teremtmények.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Sable Peak', 'Sable_Peak.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Sinners Consumed - Elpusztított bűnösök', 'Sinners Consumed - Elpusztított bűnösök.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Solo Leveling 9.', 'Solo Leveling 9..jpg', NULL, 1, 9, 4, 2, 1, 0.0),
('Sorozatgyilkos nők', 'Sorozatgyilkos nők.jpg', NULL, 1, 7, 7, 1, 1, 0.0),
('Sosem menekülsz!', 'Sosem menekülsz!.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Steel Princess', 'Steel Princess.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Szent László országa', 'Szent László országa.jpg', NULL, 1, 7, 7, 1, 1, 0.0),
('Szerintem', 'Szerintem.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Szuperszemélyiség', 'Szuperszemélyiség.jpg', NULL, 1, 15, 15, 1, 1, 0.0),
('Szénhidrátdiéta a gyakorlatban', 'Szénhidrátdiéta a gyakorlatban.jpg', NULL, 1, 8, 8, 1, 1, 0.0),
('Sátántangó', 'Sátántangó.jpg', NULL, 1, 3, 1, 1, 1, 4.8),
('Süticsata a cicakávézóban', 'Süticsata a cicakávézóban.jpg', NULL, 1, 9, 9, 1, 1, 0.0),
('Taming 7', 'Taming 7.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Tejtermékek kis szakácskönyve', 'Tejtermékek kis szakácskönyve.jpg', NULL, 1, 6, 2, 1, 1, 0.0),
('Tested és lelkem', 'Tested és lelkem.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('The Boyfriend', 'The Boyfriend.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('The Defender - A védő', 'The Defender - A védő.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('The Things Gods Break - Az istenek pusztítása', 'The Things Gods Break - Az istenek pusztítása.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('the rivaled crown', 'the_rivaled_crown.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Twisted Love - Ava & Alex', 'Twisted Love - Ava & Alex.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Tökéletes gyanúsított', 'Tökéletes gyanúsított.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Történelem 1', 'Történelem 1.jpg', NULL, 1, 7, 7, 1, 1, 0.0),
('Tövisek a toszkán liliomok között - (Különleges kiadás)', 'Tövisek a toszkán liliomok között - (Különleges kiadás).jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Tövisek a toszkán liliomok között', 'Tövisek a toszkán liliomok között.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Under Your Scars', 'Under Your Scars.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Vad tekintet', 'Vad_tekintet.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Vicious Prince - Gonosz herceg', 'Vicious Prince - Gonosz herceg.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Vidéki ballada az Amerikai Álomról', 'Vidéki ballada az Amerikai Álomról.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Visszatérés', 'Visszatérés.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Voracious', 'Voracious.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Várólista és további felnőttmesék', 'Várólista és további felnőttmesék.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Where the Library Hides - A könyvtár rejteke', 'Where the Library Hides - A könyvtár rejteke.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Wild Reverence - Vad áhitat', 'Wild Reverence - Vad áhitat.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Zeusz - A vízimentő kutya', 'Zeusz - A vízimentő kutya.jpg', NULL, 1, 9, 9, 1, 1, 0.0),
('Árnyhercegnő - Zodiákus Akadémia 4.', 'Árnyhercegnő - Zodiákus Akadémia 4..jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Átkozott örökség', 'Átkozott örökség.jpg', NULL, 1, 9, 4, 1, 1, 0.0),
('Éjfél könyvtár', 'Éjfél könyvtár.jpg', NULL, 1, 9, 1, 1, 1, 0.0),
('Éjféli titok', 'Éjféli titok.jpg', NULL, 1, 9, 6, 1, 1, 0.0),
('Érettségi témakörök vázlata történelemből - középszinten', 'Érettségi témakörök vázlata történelemből - középszinten.jpg', NULL, 1, 8, 7, 1, 1, 0.0),
('Így is ehetünk', 'Így is ehetünk.jpg', NULL, 1, 8, 2, 1, 1, 0.0),
('Írtam egy könyvet rólad', 'Írtam egy könyvet rólad.jpg', NULL, 1, 8, 11, 1, 1, 0.0),
('Úgy, ahogy vagy', 'Úgy, ahogy vagy.jpg', NULL, 1, 9, 3, 1, 1, 0.0),
('Őrület határán', 'Őrület határán.jpg', NULL, 1, 9, 6, 1, 1, 0.0);